### ISSUE TITLE
Vacation form

### ISSUE THREAD

**Issue by AnH13-6** [AnH13-6/capstone-project#1]
As a user
I want to register a vacation
so that I can later add entries to it

![Image](https://user-images.githubusercontent.com/60193027/190607281-6c611c79-31ad-421a-a77b-83a620072cda.png)

## Acceptance criteria (ac)

- [x] there is a form on the page with one input and one button
- [x] when the submit-button ist clicked, the vacation will be registered (added to a list of vacations)

## Tasks

- [x] create a branch and switch to it
- [x] create an input field
- [x] create a button
- [x] add eventlistener to the button to submit the form
