### ISSUE TITLE
Entry form

### ISSUE THREAD

**Issue by AnH13-6** [AnH13-6/capstone-project#2]
As a user
I want to add a text entry under a selected vacation
so that I can read them later

![Image](https://user-images.githubusercontent.com/60193027/190612452-48f24f01-db72-4ac8-9a7d-00921d08f89c.png)

## ac

- [x] there is a form on a page with a date picker, a selection of vacations and a text input
- [x] there's a button that will submit the form when clicked

## tasks

- [x] create a new branch and switch to it
- [x] add a date picker
- [x] add a vacation selection
- [x] add a text input
- [x] add a button
- [x] add an evenListener to submit the form

**Comment by ben-me** [comment]
Looks like a good user story.

Some things might be worth thinking about:
- there are no buttons/links that will be used for navigation to different pages. How do you get to and from this page to the others?
- should the form reset when submitting?
- should there be restrictions to the form (forbidden symbols, only empty spaces etc)?
- can you select a date/vacation that already has an entry and if so, does the app need to do anything (reminder/error)?

These are just optional so let me know what you think. If you don't need them I will mark the story as done in slack.

**Comment by AnH13-6** [comment]
Thanks Ben! I will add the navigation in the next step, as I try to work with the smallest possible parts of the app. I haven't really thought what will happen after the submit, good point! I will also add edit and delete buttons for entries and vacations later on!

**Comment by ben-me** [comment]
Also just updated a point about adding restictions for the input field. For example the user should not be able to only save multiple spaces as text. The app could then give out an error or hint that this is invalid.

I marked your story as done.

**Comment by AnH13-6** [comment]
Thanks! You are right about the restrictions! I will remember to add that
